package secure;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author Chengpeng
 */
public class TodaysSchedule extends javax.swing.JFrame {

    /**
     * Creates new form TodaysSchedule
     */
    public TodaysSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Schedule = new javax.swing.JPanel();
        ScheduleLab = new javax.swing.JLabel();
        btnProductA = new javax.swing.JButton();
        btnProductB = new javax.swing.JButton();
        btnProductC = new javax.swing.JButton();
        btnOverallScen = new javax.swing.JButton();
        jScrollPane_Message = new javax.swing.JScrollPane();
        tabSchedule = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Today's Schedule");

        jPanel_Schedule.setBackground(java.awt.Color.decode("#003333"));
        jPanel_Schedule.setPreferredSize(new java.awt.Dimension(1000, 600));

        ScheduleLab.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ScheduleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScheduleLab.setText("Today's Schedule");
        ScheduleLab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnProductA.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnProductA.setText("Product A");
        btnProductA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductAActionPerformed(evt);
            }
        });

        btnProductB.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnProductB.setText("Product B");
        btnProductB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductBActionPerformed(evt);
            }
        });

        btnProductC.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnProductC.setText("Product C");
        btnProductC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductCActionPerformed(evt);
            }
        });

        btnOverallScen.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnOverallScen.setText("Overall Scenario");
        btnOverallScen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverallScenActionPerformed(evt);
            }
        });

        tabSchedule.setBackground(java.awt.Color.decode("#CCFFFF"));
        tabSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Manpower", "CompletedCases", "Timescale"
            }
        ));
        tabSchedule.setPreferredSize(new java.awt.Dimension(1000, 600));
        jScrollPane_Message.setViewportView(tabSchedule);

        btnExit.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ScheduleLayout = new javax.swing.GroupLayout(jPanel_Schedule);
        jPanel_Schedule.setLayout(jPanel_ScheduleLayout);
        jPanel_ScheduleLayout.setHorizontalGroup(
            jPanel_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ScheduleLayout.createSequentialGroup()
                .addComponent(jScrollPane_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 409, Short.MAX_VALUE))
            .addGroup(jPanel_ScheduleLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOverallScen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScheduleLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ScheduleLayout.setVerticalGroup(
            jPanel_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ScheduleLayout.createSequentialGroup()
                .addComponent(jScrollPane_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ScheduleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductA)
                .addGap(18, 18, 18)
                .addComponent(btnProductB)
                .addGap(18, 18, 18)
                .addComponent(btnProductC)
                .addGap(18, 18, 18)
                .addComponent(btnOverallScen)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(603, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOverallScenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverallScenActionPerformed
        DefaultTableModel model=(DefaultTableModel) tabSchedule.getModel();
        model.setRowCount(0);
        String sql="Select * from schedule";
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/onlinebilling","root","eyedk75A");
        Statement stmt=con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next())
        {
            String type = rs.getString("Type");
            String manpower = rs.getString("Manpower");
            String cases = rs.getString("CompletedCases");
            String time = rs.getString("Timescale");
            model.addRow(new Object []{type,manpower,cases,time});
        }
        }
        catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        
    }//GEN-LAST:event_btnOverallScenActionPerformed

    private void btnProductAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductAActionPerformed
        DefaultTableModel model=(DefaultTableModel) tabSchedule.getModel();
        model.setRowCount(0);
        String sql="Select * from schedule where Type = 'ProductA'";
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/onlinebilling","root","eyedk75A");
        Statement stmt=con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next())
        {
            String type = rs.getString("Type");
            int manpower = rs.getInt("Manpower");
            int cases = rs.getInt("CompletedCases");
            int time = rs.getInt("Timescale");
            model.addRow(new Object []{type,manpower,cases,time});
        }
        }
        catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnProductAActionPerformed

    private void btnProductBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductBActionPerformed
        DefaultTableModel model=(DefaultTableModel) tabSchedule.getModel();
        model.setRowCount(0);
        String sql="Select * from schedule where Type = 'ProductB'";
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/onlinebilling","root","eyedk75A");
        Statement stmt=con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next())
        {
            String type = rs.getString("Type");
            String manpower = rs.getString("Manpower");
            String cases = rs.getString("CompletedCases");
            String time = rs.getString("Timescale");
            model.addRow(new Object []{type,manpower,cases,time});
        }
        }
        catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnProductBActionPerformed

    private void btnProductCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductCActionPerformed
        DefaultTableModel model=(DefaultTableModel) tabSchedule.getModel();
        model.setRowCount(0);
        String sql="Select * from schedule where Type = 'ProductC'";
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/onlinebilling","root","eyedk75A");
        Statement stmt=con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next())
        {
            String type = rs.getString("Type");
            String manpower = rs.getString("Manpower");
            String cases = rs.getString("CompletedCases");
            String time = rs.getString("Timescale");
            model.addRow(new Object []{type,manpower,cases,time});
        }
        }
        catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnProductCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodaysSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodaysSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodaysSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodaysSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodaysSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScheduleLab;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOverallScen;
    private javax.swing.JButton btnProductA;
    private javax.swing.JButton btnProductB;
    private javax.swing.JButton btnProductC;
    private javax.swing.JPanel jPanel_Schedule;
    private javax.swing.JScrollPane jScrollPane_Message;
    private javax.swing.JTable tabSchedule;
    // End of variables declaration//GEN-END:variables
}
